from typing import Any, Callable


class BaseScheduler: ...


class BackgroundScheduler(BaseScheduler):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def start(self) -> None: ...
    def add_job(self, func: Callable[..., Any], trigger: Any, id: str = ..., replace_existing: bool = ...) -> None: ...
    def remove_job(self, job_id: str) -> None: ...


class triggers:
    class cron:
        def CronTrigger(**kwargs: Any) -> Any: ...
